---
- hosts: server
  gather_facts: false
  sudo: true
  vars_files:
    - vars.yml
  
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted

  - name: restart fail2ban
    service: name=fail2ban state=restarted

  tasks:
  - name: Update APT packages cache
    apt: update_cache=yes

  - name: upgrade APT to the latest packages
    apt: upgrade=safe

  - name: create user
    user: home=/home/{{ user }} name={{ user }} state=present

  - name: copy user ssh key
    authorized_key: user={{ user }} key="{{ item }}"
    with_file: 
      - files/ssh/{{ user }}.pub

  - name: disable password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: restart ssh

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present
    notify: restart ssh

  - name: install security-relaed packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items:
      - fail2ban
      - tripwire
      - unattended-upgrades

  - name: setup ufw
    ufw: state=enabled policy=deny

  - name: allow ssh traffic
    ufw: rule=allow port={{ ssh_port }} proto=tcp
